module FSharpHomeworks.Tests.Factorial

open Introduction
open Expecto

/// <summary>
/// Function that compute factorial.
/// </summary>
/// <param name="count">
/// Number whose factorial will be calculated.
/// </param>
let factorial count =
    let rec recFactorial count acc =
        if count < 1 then
            acc
        else
            recFactorial (count - 1) (acc * count)

    recFactorial count 1

/// <summary>
/// Check result.
/// </summary>
/// <param name="count">Factorial argument.</param>
/// <param name="result">Actual factorial result.</param>
let checkResult count result =
    "Results must be the same" |> Expect.equal (factorial count) result

/// <summary>
/// Make test.
/// </summary>
/// <param name="count">
/// Factorial parameter.
/// </param>
/// <remarks>
/// It is assumed that the argument will be generated by FSCheck.
/// </remarks>
let makeTest count =
    Factorial.run count |> checkResult count

/// <summary>
/// Factorial tests.
/// </summary>
let tests =
    [ makeTest |> testProperty "factorial test" ]
    |> testList "Introduction.Factorial tests"
