name: Build master

on: [push, pull_request]

jobs:
    win-build:
        name: Windows Build
        runs-on: windows-latest
        defaults:
            run:
                shell: cmd
        steps:
            - name: System Info
              run: systeminfo

            - uses: actions/checkout@v2

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v1

            - name: Build
              run: ./build.cmd
