name: Build master

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
    # Not specifying a version will attempt to install via global.json
    - name: Use .NET Core global.json
      uses: actions/setup-dotnet@v1

    - name: Build
      run: ./build.cmd
